version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=YOUR_API_KEY
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=YOUR_BACKEND_URL
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app