version: '3.8'

services:
  backend:
    image: jackdriscoll13/carwash:backend-latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSyD8ztW4LX_5HD9Tg19Q13NXWmvGnP77UtE
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: jackdriscoll13/carwash:frontend-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app