version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSyD8ztW4LX_5HD9Tg19Q13NXWmvGnP77UtE
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8000
    
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app